CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ratings
(
    id     INTEGER PRIMARY KEY,
    rating VARCHAR(5)
);

CREATE TABLE IF NOT EXISTS types_friendship
(
    id   INTEGER PRIMARY KEY,
    type VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(100),
    login    VARCHAR(100),
    email    VARCHAR(100),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS films
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200),
    description VARCHAR(200),
    releaseDate DATE,
    duration    INTEGER,
    rating      INTEGER,
    FOREIGN KEY (rating) REFERENCES ratings (id)
);

CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  INTEGER NOT NULL,
    genre_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, genre_id),
    FOREIGN KEY (film_id) REFERENCES films (id),
    FOREIGN KEY (genre_id) REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS film_likes
(
    film_id INTEGER NOT NULL,
    user_id INTEGER NOT NULL,
    PRIMARY KEY (film_id, user_id),
    FOREIGN KEY (film_id) REFERENCES films (id),
    FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user1_id           INTEGER NOT NULL,
    user2_id           INTEGER NOT NULL,
    type_friendship_id INTEGER,
    PRIMARY KEY (user1_id, user2_id),
    FOREIGN KEY (user1_id) REFERENCES users (id),
    FOREIGN KEY (user2_id) REFERENCES users (id),
    FOREIGN KEY (type_friendship_id) REFERENCES types_friendship (id)
);